# Docker-Compose configuration file.

version: '3'

services:
  web:
    restart: always
    image: nginx:stable-alpine
    container_name: web
    volumes:
      - ./html:/usr/share/nginx/html
      - /var/log/nginx/log:/var/log/nginx/log
    ports:
      - 80:80
    networks:
      - public

networks:
  public:
    driver: bridge
