# Docker-Compose configuration file.

version: '2'

services:
    # NGINX preview of 'npm run build' contents
  preview:
    image: nginx:stable-alpine
    container_name: starter-web-preview
    volumes:
      - .:/usr/share/nginx/html
    ports:
      - 80:80
